export default {
  page: 1,
  results: [
    {
      adult: false,
      backdrop_path: "/drulhSX7P5TQlEMQZ3JoXKSDEfz.jpg",
      genre_ids: [18, 14, 878],
      id: 581389,
      original_language: "ko",
      original_title: "승리호",
      overview:
        "2092년, 지구는 병들고 우주 위성궤도에 인류의 새로운 보금자리인 UTS가 만들어졌다. 돈 되는 일이라면 뭐든 하는 조종사 태호, 과거 우주 해적단을 이끌었던 장선장, 갱단 두목이었지만 이제는 기관사가 된 타이거 박, 평생 이루고 싶은 꿈을 가진 작살잡이 로봇 업동이, 이들은 우주쓰레기를 주워 돈을 버는 청소선 승리호의 선원들이다. 어느 날 사고 우주정을 수거한 승리호는 그 안에 숨어있던 대량살상무기로 알려진 인간형 로봇 도로시를 발견한다. 돈이 절실한 선원들은 도로시를 거액의 돈과 맞바꾸기 위한 위험한 거래를 계획하는데...",
      popularity: 1428.152,
      poster_path: "/vOefWMYqC1S3aiCTD5MD8HeXl0Y.jpg",
      release_date: "2021-02-05",
      title: "승리호",
      video: false,
      vote_average: 7.2,
      vote_count: 488,
    },
    {
      adult: false,
      backdrop_path: "/h9DIlghaiTxbQbt1FIwKNbQvEL.jpg",
      genre_ids: [28, 12, 53],
      id: 581387,
      original_language: "ko",
      original_title: "백두산",
      overview:
        "대한민국 관측 역사상 최대 규모의 백두산 폭발 발생. 갑작스러운 재난에 한반도는 순식간에 아비규환이 되고, 남과 북 모두를 집어삼킬 추가 폭발이 예측된다. 사상 초유의 재난을 막기 위해 전유경은 백두산 폭발을 연구해 온 지질학 교수 강봉래의 이론에 따른 작전을 계획하고, 전역을 앞둔 특전사 EOD 대위 조인창이 남과 북의 운명이 걸린 비밀 작전에 투입된다. 작전의 키를 쥔 북한 무력부 소속 일급 자원 리준평과 접선에 성공한 인창. 하지만 준평은 속을 알 수 없는 행동으로 인창을 곤란하게 만든다. 한편, 인창이 북한에서 펼쳐지는 작전에 투입된 사실도 모른 채 서울에 홀로 남은 최지영은 재난에 맞서 살아남기 위해 고군분투하고 그 사이, 백두산 마지막 폭발까지의 시간은 점점 가까워 가는데…",
      popularity: 970.94,
      poster_path: "/1n5q3XpEhCe7TnGHzsHs5pwVT8O.jpg",
      release_date: "2019-12-19",
      title: "백두산",
      video: false,
      vote_average: 6.5,
      vote_count: 230,
    },
    {
      adult: false,
      backdrop_path: "/d2UxKyaJ5GgzuHaSsWinFfv3g6L.jpg",
      genre_ids: [28, 27, 53],
      id: 581392,
      original_language: "ko",
      original_title: "반도",
      overview:
        "전대미문의 재난 이후 4년이 흐른 대한민국은 버려진 땅이 되어버렸다. 사람들은 고립된 섬이 된 반도에 갇혔고 누구의 생사도 확인할 수 없는 상황에서 정석은 피할 수 없는 미션을 받고 한국 땅에 다시 발을 들인다. 정석은 미지의 세계인 그곳에서 예상치 못한 습격을 받고 일촉즉발의 순간 ‘반도’의 생존자들을 만나게 된다.",
      popularity: 291.358,
      poster_path: "/cmzfmGxXxSF716SYBW6seMgxMWE.jpg",
      release_date: "2020-07-15",
      title: "반도",
      video: false,
      vote_average: 7,
      vote_count: 1378,
    },
    {
      adult: false,
      backdrop_path: "/a8ppJJIQmEJcLSFfhxupc4aT4KW.jpg",
      genre_ids: [18, 28, 53],
      id: 571785,
      original_language: "ko",
      original_title: "사냥의 시간",
      overview:
        "희망 없는 도시, 감옥에서 출소한 준석은 가족 같은 친구들인 장호와 기훈 그리고 상수와 함께 무모한 작전을 계획한다. 새로운 인생을 향한 부푼 꿈도 잠시 이들을 뒤쫓는 정체불명의 추격자가 나타나면서 목숨마저 위협받게 된다. 서로가 세상의 전부인 네 친구들은 놈의 사냥에서 벗어날 수 있을까?",
      popularity: 263.911,
      poster_path: "/iF1eloJBtw0frs2EeshncF2oRCT.jpg",
      release_date: "2020-04-10",
      title: "사냥의 시간",
      video: false,
      vote_average: 7.3,
      vote_count: 173,
    },
    {
      adult: false,
      backdrop_path: "/TU9NIjwzjoKPwQHoHshkFcQUCG.jpg",
      genre_ids: [35, 53, 18],
      id: 496243,
      original_language: "ko",
      original_title: "기생충",
      overview:
        "전원 백수로 살 길 막막하지만 사이는 좋은 기택 가족. 장남 기우에게 명문대생 친구가 연결시켜 준 고액 과외 자리는 모처럼 싹튼 고정수입의 희망이다. 온 가족의 도움과 기대 속에 박 사장 집으로 향하는 기우. 글로벌 IT기업의 CEO인 박 사장의 저택에 도착하자 젊고 아름다운 사모님 연교와 가정부 문광이 기우를 맞이한다. 큰 문제 없이 박 사장의 딸 다혜의 과외를 시작한 기우. 그러나 이렇게 시작된 두 가족의 만남 뒤로, 걷잡을 수 없는 사건이 기다리고  있는데.....",
      popularity: 168.108,
      poster_path: "/v0nlHB0wDevL54Me9V9lB6QdPk2.jpg",
      release_date: "2019-05-30",
      title: "기생충",
      video: false,
      vote_average: 8.5,
      vote_count: 11114,
    },
    {
      adult: false,
      backdrop_path: "/7cGsa6sqTFsrws322p0QaIe7GUX.jpg",
      genre_ids: [28, 27],
      id: 571627,
      original_language: "ko",
      original_title: "사자",
      overview:
        "어린 시절 아버지의 갑작스런 죽음으로 신의 존재를 부정하고 자기 자신만 믿기로 한 용후. 세월이 흘러 세계 격투기 챔피언이 된 용후는 어느 날 자신의 손바닥에 생긴 성흔을 발견한다. 고통스런 성흔을 없애기 위해 안 신부를 찾아간 용후는 구마 의식 중인 안 신부를 만나고, 위기에 처한 안신부를 자신의 성흔과 격투기 실력으로 구하게 된다. 용후는 자신의 능력을 부인하면서도, 점차 성흔의 힘을 알게 되고, 안신부와의 유대감도 조금씩 깊어지며, 구마동행을 하게 된다. 사악한 절대 악 ‘지신’은 안 신부와 용후가 구마했던 민주를 결국 죽이고, 앞으로도 더 많은 사람들을 이용하며 사람들을 죽일 계획을 세운다. 안신부와 용후는 지신을 처단하려 하지만, 안신부는 지신의 공격을 받고 죽을 위기에 처하고, 용후는 거부하던 신의 힘을 받아들이고 지신과 맞서는데…",
      popularity: 129.404,
      poster_path: "/mIYX1mfBqX9SsDB6k10AFAiRp2Z.jpg",
      release_date: "2019-07-31",
      title: "사자",
      video: false,
      vote_average: 6.5,
      vote_count: 151,
    },
    {
      adult: false,
      backdrop_path: "/fVpFOcQyHJM2di9upgSIwWD5wac.jpg",
      genre_ids: [28, 27, 53],
      id: 396535,
      original_language: "ko",
      original_title: "부산행",
      overview:
        "별거 중인 펀드 매니저 석우는 소원해진 딸 수안의 생일 소원을 들어주기 위해 아내가 있는 부산행 KTX에 오른다. 이내 열차는 좀비의 침투와 감염으로 아수라장으로 변하고, 전국적 재난 뉴스를 차내에서 접한 승객들의 생존가능성은 유일하게 초기 대응에 성공한 도시 부산까지 살아남은 채 도착할 수 있느냐에 달리게 된다. 열차에 몸을 실은 석우와 딸 수안, 상화와 성경 커플, 고등학생 영국, 진희, 그리고 노숙자와 중년의 비즈니스맨 용석은 감염된 사람들의 공격을 피해 열차 안에서 사투를 벌인다.",
      popularity: 109.587,
      poster_path: "/nCrh5EQYiYXEIFNrfb4ISm7TOOo.jpg",
      release_date: "2016-07-20",
      title: "부산행",
      video: false,
      vote_average: 7.8,
      vote_count: 4638,
    },
    {
      adult: false,
      backdrop_path: "/wyv2Y9vXYJwJzF6cNVuVwVOsOUj.jpg",
      genre_ids: [18, 14, 28],
      id: 397567,
      original_language: "ko",
      original_title: "신과함께-죄와 벌",
      overview:
        "살인, 나태, 거짓, 불의, 배신, 폭력, 천륜 7개의 지옥에서 7번의 재판을 무사히 통과한 망자만이 환생하여 새로운 삶을 시작할 수 있다. 화재 사고 현장에서 여자아이를 구하고 죽음을 맞이한 소방관 자홍, 그의 앞에 저승차사 해원맥과 덕춘이 나타난다. 자신의 죽음이 아직 믿기지도 않는데 덕춘은 정의로운 망자이자 귀인이라며 그를 치켜세운다. 저승으로 가는 입구, 초군문에서 그를 기다리는 또 한 명의 차사 강림, 그는 차사들의 리더이자 앞으로 자홍이 겪어야 할 7개의 재판에서 변호를 맡아줄 변호사이기도 하다. 염라대왕에게 천년 동안 49명의 망자를 환생시키면 자신들 역시 인간으로 환생시켜 주겠다는 약속을 받은 삼차사들, 그들은 자신들이 변호하고 호위해야 하는 48번째 망자이자 19년 만에 나타난 의로운 귀인 자홍의 환생을 확신하지만, 각 지옥에서 자홍의 과거가 하나 둘씩 드러나면서 예상치 못한 고난과 맞닥뜨리는데…",
      popularity: 90.38,
      poster_path: "/5j2YVF7VouLG0Ze96SEsj4DnVQM.jpg",
      release_date: "2017-12-20",
      title: "신과함께-죄와 벌",
      video: false,
      vote_average: 8,
      vote_count: 373,
    },
    {
      adult: false,
      backdrop_path: "/v648cPRS5xPCiaSqgTlMiVzDm6o.jpg",
      genre_ids: [10749, 18],
      id: 570503,
      original_language: "ko",
      original_title: "유열의 음악앨범",
      overview:
        "1994년 가수 유열이 라디오 DJ를 처음 진행하던 날, 엄마가 남겨준 빵집에서 일하던 미수는 우연히 찾아 온 현우를 만나 설레는 감정을 느끼게 되지만 뜻하지 않은 사건으로 인해 연락이 끊기게 된다. 다시 기적처럼 마주친 두 사람은 설렘과 애틋함 사이에서 마음을 키워 가지만 서로의 상황과 시간은 자꾸 어긋나기만 한다. 계속되는 엇갈림 속에서도 라디오 ‘유열의 음악앨범’과 함께 우연과 필연을 반복하는 두 사람… 함께 듣던 라디오처럼 그들은 서로의 주파수를 맞출 수 있을까?",
      popularity: 88.332,
      poster_path: "/rt8yDvXSnk9CMDJeNYh9lv6kPMt.jpg",
      release_date: "2019-08-28",
      title: "유열의 음악앨범",
      video: false,
      vote_average: 7.9,
      vote_count: 132,
    },
    {
      adult: false,
      backdrop_path: "/sZ5qDlUT2PbMGrspLFvJ68jlje8.jpg",
      genre_ids: [28],
      id: 557968,
      original_language: "ko",
      original_title: "리벤져",
      overview:
        "극악무도한 사형수들을 격리시켜 놓은, 어떠한 법도 상식도 통하지 않는 죽음의 섬 수라도. 이곳을 지배하는 절대악 쿤을 잡기 위해 스스로 악마가 되는 길을 택해 사형수가 되어 수라도에 들어온 전직 특수경찰 율. 율은 쿤의 아지트를 찾던 중 우연히 마주친 말리와 바우로 인해 과거의 신분이 들통나게 되고 모두가 죽이고 싶어하는 살해 대상으로 지목된다. 더 이상 물러날 곳이 없는 율은 복수를 위해 목숨을 건 반격을 시작하는데...",
      popularity: 97.086,
      poster_path: "/gCvnctGVnybiPHGEB9wjOtvU5p6.jpg",
      release_date: "2018-12-06",
      title: "리벤져",
      video: false,
      vote_average: 5.4,
      vote_count: 85,
    },
    {
      adult: false,
      backdrop_path: "/10LqBLDzbR9CBPnIDDhFL0dNIAV.jpg",
      genre_ids: [35, 18],
      id: 629277,
      original_language: "ko",
      original_title: "차인표",
      overview:
        "화려한 날들은 갔다. 그것도 제법 오래전에. 하지만 여전히 과거의 영광에 젖어 사는 배우 차인표. 그의 세상이 느닷없이 무너진다. 드디어 정신 차릴 순간이 왔단 말인가.",
      popularity: 76.952,
      poster_path: "/sSoagGDAy1i8Fpky9JQDyMNWeEJ.jpg",
      release_date: "2021-01-01",
      title: "차인표",
      video: false,
      vote_average: 6.9,
      vote_count: 18,
    },
    {
      adult: false,
      backdrop_path: "/4PS3QS70Jt1WHhgYXGeogTUjl1G.jpg",
      genre_ids: [80, 28, 18],
      id: 497370,
      original_language: "ko",
      original_title: "마약왕",
      overview:
        "마약도 수출하면 애국이 되던 1970년대 대한민국, 하급 밀수업자였던 이두삼은 우연히 마약 밀수에 가담했다가 마약 제조와 유통 사업에 본능적으로 눈을 뜨게 되면서 사업에 뛰어든다. 뛰어난 눈썰미, 빠른 위기대처능력, 신이 내린 손재주로 단숨에 마약업을 장악한 이두삼. 사업적인 수완이 뛰어난 로비스트 김정아가 합류하면서 그가 만든 마약은 '메이드인 코리아'라는 브랜드를 달게 된다. 마침내 이두삼은 대한민국을 넘어 아시아까지 세력을 확장하며 백색 황금의 시대를 열게 된다 한편, 마약으로 인해 세상은 점점 불안해지기 시작하고 승승장구하는 이두삼을 주시하는 한 사람 김인구가 움직이기 시작하는데…",
      popularity: 71.244,
      poster_path: "/vXqDNIp7CrUpkcBc8eMBtDPch4J.jpg",
      release_date: "2018-12-19",
      title: "마약왕",
      video: false,
      vote_average: 6.3,
      vote_count: 68,
    },
    {
      adult: false,
      backdrop_path: "/CLThrvZR4DuuslyW6ECuwebwkm.jpg",
      genre_ids: [10749, 18, 53],
      id: 471335,
      original_language: "ko",
      original_title: "치즈인더트랩",
      overview:
        "부드러운 미소 뒤에 숨겨진 싸늘한 모습. 피하고 싶은 ‘유정(박해진)’ 선배가 갑자기 나에게 다가와 말을 걸기 시작했다.  함께 밥 먹고, 함께 과제하고, 조별 숙제 핑계로 영화도 보고... 그가 달라진 걸까. 아님 다른 꿍꿍이가 있는 걸까.  아니면 정말 나를..?  완벽하지만 위험한 선배의 달콤한 덫에 걸렸다!",
      popularity: 53.543,
      poster_path: "/cRKHelmLoTpYSERZWaE3fITaixg.jpg",
      release_date: "2018-03-14",
      title: "치즈인더트랩",
      video: false,
      vote_average: 6.1,
      vote_count: 20,
    },
    {
      adult: false,
      backdrop_path: "/uFwnUQ3ZwE5EbBEDBzs1bRPlOx8.jpg",
      genre_ids: [28, 18],
      id: 200085,
      original_language: "ko",
      original_title: "감기",
      overview:
        "밀입국 노동자들을 분당으로 실어 나른 남자가 원인불명의 바이러스에 감염되어 사망한다. 환자가 사망한지 채 24시간이 되지 않아 분당의 모든 병원에서 동일한 환자들이 속출한다. 사망자들은 기하급수적으로 늘어나지만 분당의 시민들은 무방비상태로 바이러스에 노출된다. 감염의 공포가 대한민국을 엄습하고, 호흡기를 통해 초당 3.4명 감염, 36시간 내 사망에 이르는 사상 최악의 바이러스에 정부는 2차 확산을 방지하기 위해 국가 재난사태를 발령, 급기야 도시 폐쇄라는 초유의 결정을 내린다. 피할 새도 없이 격리된 사람들은 일대혼란에 휩싸이게 되고, 대재난 속 사랑하는 이들을 구하기 위한 사람들과 죽음에서 살아 남기 위한 사람들은 목숨을 건 사투를 시작하는데…",
      popularity: 54.163,
      poster_path: "/7fQlPXebfjEqjysW3rv4RyNplih.jpg",
      release_date: "2013-08-14",
      title: "감기",
      video: false,
      vote_average: 7.5,
      vote_count: 831,
    },
    {
      adult: false,
      backdrop_path: "/fhQpVYg35LSKAY0rJBQ1sukAU1W.jpg",
      genre_ids: [28],
      id: 569016,
      original_language: "ko",
      original_title: "언니",
      overview:
        "부모 없이 발달장애인 동생을 키우는 인애는 경호원으로 일하는 중 과잉방어로 교도소에 수감된다. 출소 후 동생과 평범한 삶을 꿈꿨으나, 동생이 갑자기 사라진다. 학교와 경찰 누구도 도움을 주지않자 은혜를 직접 찾아 나선다. 그동안 몰랐던 동생의 비밀을 알게 되면서 분노가 폭발한다.",
      popularity: 54.275,
      poster_path: "/resWkxhn67V3EGDXz5UiYr2BuwK.jpg",
      release_date: "2019-01-01",
      title: "언니",
      video: false,
      vote_average: 7.2,
      vote_count: 64,
    },
    {
      adult: false,
      backdrop_path: "/iJtsrvr9fWPpx9QO3PwuqMz58wy.jpg",
      genre_ids: [18],
      id: 570508,
      original_language: "ko",
      original_title: "증인",
      overview:
        "신념은 잠시 접어두고 현실을 위해 속물이 되기로 마음먹은 민변 출신의 대형 로펌 변호사 순호. 파트너 변호사로 승진할 수 있는 큰 기회가 걸린 사건의 변호사로 지목되자 살인 용의자의 무죄를 입증하기 위해 유일한 목격자인 자폐 소녀 지우를 증인으로 세우려 한다. 자기만의 세계에 빠져 의사소통이 어려운 지우. 순호는 사건 당일 목격한 것을 묻기 위해 지우를 찾아가지만, 제대로 된 인사조차 나누지 못한다. 하지만 그날의 이야기를 듣기 위해 지우에게 다가가려 노력하는 순호는, 시간이 흐를수록 조금씩 지우에 대해 이해하게 되지만 이제 두 사람은 법정에서 변호사와 증인으로 마주해야 하는데…",
      popularity: 55.494,
      poster_path: "/hmce0JRznzhwlIeHZctLZnxTwA8.jpg",
      release_date: "2019-02-13",
      title: "증인",
      video: false,
      vote_average: 7.7,
      vote_count: 35,
    },
    {
      adult: false,
      backdrop_path: "/x5xxJhbS2PCdwf8n4NzYZISspN1.jpg",
      genre_ids: [878, 28, 53, 18],
      id: 467824,
      original_language: "ko",
      original_title: "인랑",
      overview:
        "남북한 정부가 통일준비 5개년 계획을 선포한 후, 강대국의 경제 제재가 이어지고,  민생이 악화되는 등 지옥 같은 시간이 이어지고 있는 혼돈의 2029년. 자원은 고갈되고 빈곤층이 늘어나면서 도시가 황폐해지자, 통일에 반대하는 반정부 무장테러단체 섹트가 등장한다. 섹트를 진압하기 위해 설립된 대통령 직속의 새로운 경찰조직 특기대는 정국의 주도권을 장악하고, 이에 입지가 줄어든 정보기관공안부는 특기대를 말살할 음모를 꾸민다. 절대 권력기관 간의 피비린내 나는 암투 사이, 특기대 내 비밀조직 인랑에 대한 소문이 떠도는데...",
      popularity: 63.977,
      poster_path: "/9kAjGEOLWF1FXZy5DgghdoCD4OO.jpg",
      release_date: "2018-07-25",
      title: "인랑",
      video: false,
      vote_average: 6.4,
      vote_count: 164,
    },
    {
      adult: false,
      backdrop_path: "/r4fxp9LqfCyPsnz6LFVzUn7jrVN.jpg",
      genre_ids: [18, 28],
      id: 437109,
      original_language: "ko",
      original_title: "악녀",
      overview:
        "조직의 킬러로 자란 숙희는 보스이자 연인이었던 중상의 복수를 위해 마약조직 하나를 박살낸다. 사건 직후 구속된 숙희는 국가정보원으로부터 10년간 국가를 위해 임무를 수행하면 자유를 주겠다는 거래를 제안받는다. 뱃속에 중상의 아기가 자라고 있음을 안 숙희는 새로운 삶을 위해 제안을 받아들이고 암살요원으로서의 생활을 시작한다. 한편 숙희를 철저히 감시, 통제하기 위해 국정원 요원 현수가 비밀리에 접근한다. 둘 사이의 관계가 가까워질 즈음 예상치 못한 인물의 등장으로 숙희의 거짓된 삶은 철저히 부서지기 시작한다.",
      popularity: 44.564,
      poster_path: "/2arvz5fsrE1BmlbjbBHSiLltlLq.jpg",
      release_date: "2017-06-08",
      title: "악녀",
      video: false,
      vote_average: 6.9,
      vote_count: 431,
    },
    {
      adult: false,
      backdrop_path: "/ul4WiN9EJxsMokdg7z4Y6iisvHS.jpg",
      genre_ids: [18, 14, 28],
      id: 518068,
      original_language: "ko",
      original_title: "신과함께-인과 연",
      overview:
        "천 년 동안 48명의 망자를 환생시킨 저승 삼차사, 한 명만 더 환생시키면 그들도 새로운 삶을 얻을 수 있다. 하지만 강림은 원귀였던 수홍을 자신들의 마지막 귀인으로 정한다. 저승법 상 원귀는 소멸되어야하나 염라대왕은 새로운 조건을 내걸며 강림의 제안을 수락한다. 염라의 조건은 성주신이 버티고 있어 저승 차사들이 가는 족족 실패하는 허춘삼 노인을 수홍의 재판이 끝나기 전까지 저승으로 데려오는 것. 허춘삼을 데리러 이승으로 내려간 해원맥과 덕춘, 하지만 성주신의 막강한 힘 앞에 속수무책으로 당하기만 하는데...",
      popularity: 43.285,
      poster_path: "/2ETx0U2Q5gUHtPJZiQ3hakTqyaR.jpg",
      release_date: "2018-08-01",
      title: "신과 함께 - 인과 연",
      video: false,
      vote_average: 8.1,
      vote_count: 211,
    },
    {
      adult: false,
      backdrop_path: "/9DET8yv7MYMwOWe1eR2CigFkev4.jpg",
      genre_ids: [28, 878, 18],
      id: 110415,
      original_language: "ko",
      original_title: "Snowpiercer",
      overview:
        "기상 이변으로 모든 것이 꽁꽁 얼어붙은 지구, 살아남은 사람들을 태운 기차 한 대가 끝없이 궤도를 달리고 있다. 춥고 배고픈 사람들이 바글대는 빈민굴 같은 꼬리칸, 그리고 선택된 사람들이 술과 마약까지 즐기며 호화로운 객실을 뒹굴고 있는 앞쪽칸. 열차 안의 세상은 결코 평등하지 않다. 기차가 달리기 시작한 17년째, 꼬리칸의 젊은 지도자 커티스는 긴 세월 준비해 온 폭동을 일으킨다. 기차의 심장인 엔진을 장악하고 기차 전체를 해방시키기 위해 절대권력자 윌포드가 도사리고 있는 엔진 칸을 향해 질주하는 커티스와 꼬리칸 사람들. 그들 앞에 예기치 못한 상황들이 기다리고 있는데...",
      popularity: 55.731,
      poster_path: "/pRZMtKQpP3fH84YXs02yytUk4ee.jpg",
      release_date: "2013-08-01",
      title: "설국열차",
      video: false,
      vote_average: 6.9,
      vote_count: 7134,
    },
  ],
  total_pages: 309,
  total_results: 6178,
};
