import React from "react";
import { Story } from "@storybook/react";
import CastList, { ICastList } from "./index";

export default {
  component: CastList,
  title: "CastList",
};
const Template: Story<ICastList> = (args) => <CastList {...args} />;
export const Default = Template.bind({});
Default.args = {
  castCards: [
    {
      adult: false,
      gender: 2,
      id: 28846,
      known_for_department: "Acting",
      name: "Alexander Skarsgård",
      original_name: "Alexander Skarsgård",
      popularity: 13.519,
      profile_path: "/hIuDik6KDmHLrqZWxBVdXzUw1kq.jpg",
      cast_id: 27,
      character: "Dr. Nathan Lind",
      credit_id: "5bd27583c3a3687437003310",
      order: 0,
    },
    {
      adult: false,
      gender: 1,
      id: 1356210,
      known_for_department: "Acting",
      name: "Millie Bobby Brown",
      original_name: "Millie Bobby Brown",
      popularity: 31.372,
      profile_path: "/yzfxLMcBMusKzZp9f1Z9Ags8WML.jpg",
      cast_id: 10,
      character: "Madison Russell",
      credit_id: "5b154f5dc3a368533000d528",
      order: 1,
    },
    {
      adult: false,
      gender: 1,
      id: 15556,
      known_for_department: "Acting",
      name: "Rebecca Hall",
      original_name: "Rebecca Hall",
      popularity: 16.169,
      profile_path: "/cVZaQrUY7F5khCBYdKDlEppHnQi.jpg",
      cast_id: 29,
      character: "Dr. Ilene Andrews",
      credit_id: "5bd9b264925141156c00e024",
      order: 2,
    },
    {
      adult: false,
      gender: 2,
      id: 226366,
      known_for_department: "Acting",
      name: "Brian Tyree Henry",
      original_name: "Brian Tyree Henry",
      popularity: 5.457,
      profile_path: "/1h4sYFAc1inxcV0Ljrl5v2mMskI.jpg",
      cast_id: 25,
      character: "Bernie Hayes",
      credit_id: "5bbeafae9251413d51006008",
      order: 3,
    },
    {
      adult: false,
      gender: 2,
      id: 46364,
      known_for_department: "Acting",
      name: "Shun Oguri",
      original_name: "Shun Oguri",
      popularity: 8.098,
      profile_path: "/4tfrhvqp3IGHPATor0lYE9X9UD3.jpg",
      cast_id: 32,
      character: "Ren Serizawa",
      credit_id: "5be890c90e0a263c0a031146",
      order: 4,
    },
    {
      adult: false,
      gender: 1,
      id: 1222992,
      known_for_department: "Acting",
      name: "Eiza González",
      original_name: "Eiza González",
      popularity: 21.454,
      profile_path: "/w2pZ8gLqZNguj8cqrDGbMw2Ibj0.jpg",
      cast_id: 28,
      character: "Maia Simmons",
      credit_id: "5bd9b256925141155700e422",
      order: 5,
    },
    {
      adult: false,
      gender: 2,
      id: 1139349,
      known_for_department: "Acting",
      name: "Julian Dennison",
      original_name: "Julian Dennison",
      popularity: 7.033,
      profile_path: "/9wmT8RDfJL2yKuY5AeJuDTkHSJe.jpg",
      cast_id: 9,
      character: "Josh Valentine",
      credit_id: "5b1411640e0a262dca0000ac",
      order: 6,
    },
    {
      adult: false,
      gender: 2,
      id: 129101,
      known_for_department: "Acting",
      name: "Lance Reddick",
      original_name: "Lance Reddick",
      popularity: 8.692,
      profile_path: "/22mVtEXZbpt0J7S0LhIhdkfRrZV.jpg",
      cast_id: 37,
      character: "Guillermin",
      credit_id: "5becd66d9251413cdb009fcc",
      order: 7,
    },
    {
      adult: false,
      gender: 2,
      id: 3497,
      known_for_department: "Acting",
      name: "Kyle Chandler",
      original_name: "Kyle Chandler",
      popularity: 10.177,
      profile_path: "/12ycW6JwP51RJA36mbT7ietI4Ce.jpg",
      cast_id: 11,
      character: "Mark Russell",
      credit_id: "5b154f7c0e0a262dea00a185",
      order: 8,
    },
    {
      adult: false,
      gender: 2,
      id: 76961,
      known_for_department: "Acting",
      name: "Demián Bichir",
      original_name: "Demián Bichir",
      popularity: 5.469,
      profile_path: "/sw8TqPQLbMMgLbkNNUIW649THWJ.jpg",
      cast_id: 26,
      character: "Walter Simmons",
      credit_id: "5bc82e840e0a26362e01120e",
      order: 9,
    },
    {
      adult: false,
      gender: 1,
      id: 2948491,
      known_for_department: "Acting",
      name: "Kaylee Hottle",
      original_name: "Kaylee Hottle",
      popularity: 1.958,
      profile_path: "/xpQQZgptOUI6duMMBDyCiaJ4JUv.jpg",
      cast_id: 60,
      character: "Jia",
      credit_id: "600c0d153710970041a1a056",
      order: 10,
    },
    {
      adult: false,
      gender: 2,
      id: 2603,
      known_for_department: "Acting",
      name: "Hakeem Kae-Kazim",
      original_name: "Hakeem Kae-Kazim",
      popularity: 2.092,
      profile_path: "/sVNHRm51c9toG73FUQ5k1St0vju.jpg",
      cast_id: 59,
      character: "Admiral Wilcox",
      credit_id: "600c0cedc86b3a003fbe0ca3",
      order: 11,
    },
    {
      adult: false,
      gender: 2,
      id: 1319469,
      known_for_department: "Acting",
      name: "Ronny Chieng",
      original_name: "Ronny Chieng",
      popularity: 1.428,
      profile_path: "/haFPocRfiud0Miw45HlknGMaLG5.jpg",
      cast_id: 58,
      character: "Jay Wayne",
      credit_id: "600c0cd2dd83fa0040909c38",
      order: 12,
    },
    {
      adult: false,
      gender: 2,
      id: 1178193,
      known_for_department: "Acting",
      name: "John Pirruccello",
      original_name: "John Pirruccello",
      popularity: 1.543,
      profile_path: "/5fHP9q7bLbOGpeyoKpkz6MaunMN.jpg",
      cast_id: 57,
      character: "Horace",
      credit_id: "600c0cb7813cb600427c006c",
      order: 13,
    },
    {
      adult: false,
      gender: 2,
      id: 172096,
      known_for_department: "Acting",
      name: "Chris Chalk",
      original_name: "Chris Chalk",
      popularity: 4.547,
      profile_path: "/j8IpJkLTAhalh5Q356VNojcIAtx.jpg",
      cast_id: 56,
      character: "Ben",
      credit_id: "600c0c95c86b3a003fbe0c83",
      order: 14,
    },
    {
      adult: false,
      gender: 2,
      id: 2545317,
      known_for_department: "Acting",
      name: "Conlan Casal",
      original_name: "Conlan Casal",
      popularity: 0.6,
      profile_path: "/nBbRXpuiufIXeXhHR3v9I2kEymP.jpg",
      cast_id: 72,
      character: "Apex Cybernetics Security Guard",
      credit_id: "601624c0976a23003ca463e2",
      order: 15,
    },
    {
      adult: false,
      gender: 2,
      id: 123540,
      known_for_department: "Acting",
      name: "Brad McMurray",
      original_name: "Brad McMurray",
      popularity: 1.288,
      profile_path: "/bfsTsUwYajWlVPgkcY9QzrWuVbi.jpg",
      cast_id: 73,
      character: "Apex Cybernetics Security Guard",
      credit_id: "601624cebc8657003e6c16e9",
      order: 16,
    },
    {
      adult: false,
      gender: 2,
      id: 1371541,
      known_for_department: "Acting",
      name: "Benjamin Rigby",
      original_name: "Benjamin Rigby",
      popularity: 1.166,
      profile_path: "/le5qTKDolOJBZ5mWjnx5QwNbCPA.jpg",
      cast_id: 74,
      character: "Sonar Operator",
      credit_id: "601624f10816c7003f84c7e6",
      order: 17,
    },
    {
      adult: false,
      gender: 2,
      id: 2272452,
      known_for_department: "Crew",
      name: "Nick Turello",
      original_name: "Nick Turello",
      popularity: 0.6,
      profile_path: "/hKlnldINN0J6bY3Rj9PXvjSzjMb.jpg",
      cast_id: 75,
      character: "Apex Cybernetics Armed Guard",
      credit_id: "6016250dbf0f63003e0f1642",
      order: 18,
    },
    {
      adult: false,
      gender: 2,
      id: 2881089,
      known_for_department: "Acting",
      name: "Daniel Nelson",
      original_name: "Daniel Nelson",
      popularity: 1.009,
      profile_path: "/jfVtAqELfncHRHomUrTuVVYXrg.jpg",
      cast_id: 51,
      character: "Hayworth",
      credit_id: "5fca3f64dcf875003f40b2f5",
      order: 19,
    },
    {
      adult: false,
      gender: 1,
      id: 2102960,
      known_for_department: "Acting",
      name: "Priscilla Doueihy",
      original_name: "Priscilla Doueihy",
      popularity: 0.6,
      profile_path: "/it4g13EMcqsXXggG1DYcOxQZwsA.jpg",
      cast_id: 54,
      character: "Monarch Mission Tech",
      credit_id: "600a0673d55c3d00406c465e",
      order: 20,
    },
    {
      adult: false,
      gender: 0,
      id: 2958901,
      known_for_department: "Acting",
      name: "Kei Kudo",
      original_name: "Kei Kudo",
      popularity: 0.6,
      profile_path: null,
      cast_id: 76,
      character: "HEAV Pilot",
      credit_id: "6016254428723c003dabf6c7",
      order: 21,
    },
    {
      adult: false,
      gender: 2,
      id: 1871679,
      known_for_department: "Crew",
      name: "Bradd Buckley",
      original_name: "Bradd Buckley",
      popularity: 0.98,
      profile_path: null,
      cast_id: 77,
      character: "HEAV Pilot",
      credit_id: "601625512d3721003fc35858",
      order: 22,
    },
    {
      adult: false,
      gender: 2,
      id: 1265157,
      known_for_department: "Acting",
      name: "John Walton",
      original_name: "John Walton",
      popularity: 1.38,
      profile_path: null,
      cast_id: 163,
      character: "HEAV Co-Pilot",
      credit_id: "606a97e512c6040029621ca3",
      order: 23,
    },
    {
      adult: false,
      gender: 2,
      id: 2612144,
      known_for_department: "Acting",
      name: "Daniel Tuiara",
      original_name: "Daniel Tuiara",
      popularity: 0.6,
      profile_path: "/7FQS4v8pa84ojcCuRfOzqI64NC0.jpg",
      cast_id: 164,
      character: "HEAV Co-Pilot",
      credit_id: "606a97efa14bef00792a4109",
      order: 24,
    },
    {
      adult: false,
      gender: 2,
      id: 1696636,
      known_for_department: "Crew",
      name: "David Castillo",
      original_name: "David Castillo",
      popularity: 0.6,
      profile_path: "/jlQLRRhOJB3bkXNMletYPio8pS4.jpg",
      cast_id: 78,
      character: "Maia Apex Cybernetics Guard",
      credit_id: "6016256fd96c3c00410ec397",
      order: 25,
    },
    {
      adult: false,
      gender: 2,
      id: 1298704,
      known_for_department: "Acting",
      name: "Kofi Yiadom",
      original_name: "Kofi Yiadom",
      popularity: 0.708,
      profile_path: "/uvVMFFmg26p1sd9mQaclczyunx.jpg",
      cast_id: 79,
      character: "Maia Apex Cybernetics Guard",
      credit_id: "6016257cbc8657003d6be201",
      order: 26,
    },
    {
      adult: false,
      gender: 2,
      id: 9568,
      known_for_department: "Acting",
      name: "Jim Palmer",
      original_name: "Jim Palmer",
      popularity: 1.4,
      profile_path: "/oFaoyxX8EPY6VxBJ3pVyMezseuZ.jpg",
      cast_id: 55,
      character: "Maia Apex Cybernetics Guard",
      credit_id: "600a0685d70594003d1d76af",
      order: 27,
    },
    {
      adult: false,
      gender: 2,
      id: 2958904,
      known_for_department: "Acting",
      name: "Drew Walton",
      original_name: "Drew Walton",
      popularity: 0.6,
      profile_path: "/g8byyulAZcXW5heefanHMG227pY.jpg",
      cast_id: 80,
      character: "David Lind (uncredited)",
      credit_id: "601625a7cb802800411054e7",
      order: 28,
    },
    {
      adult: false,
      gender: 1,
      id: 1692993,
      known_for_department: "Acting",
      name: "Tara Wraith",
      original_name: "Tara Wraith",
      popularity: 0.6,
      profile_path: "/7hxplRWMQy0iQPLIBVQyWL9fD6R.jpg",
      cast_id: 182,
      character: "Monarch Flight Crew (uncredited)",
      credit_id: "607b87d07a97ab0040a07b2d",
      order: 29,
    },
    {
      adult: false,
      gender: 2,
      id: 2027791,
      known_for_department: "Acting",
      name: "Jason Virgil",
      original_name: "Jason Virgil",
      popularity: 0.6,
      profile_path: "/4rMBW2yVt4uH8xrHSt9ORu3bc2C.jpg",
      cast_id: 187,
      character: "Bartender (uncredited)",
      credit_id: "607b892aab68490029ca5f05",
      order: 34,
    },
    {
      adult: false,
      gender: 1,
      id: 2524631,
      known_for_department: "Acting",
      name: "Grisel Toledo",
      original_name: "Grisel Toledo",
      popularity: 1.052,
      profile_path: null,
      cast_id: 188,
      character: "Apex Guard (uncredited)",
      credit_id: "607b896a746457005892f336",
      order: 35,
    },
    {
      adult: false,
      gender: 2,
      id: 2265521,
      known_for_department: "Acting",
      name: "Jason Szabo",
      original_name: "Jason Szabo",
      popularity: 1.38,
      profile_path: null,
      cast_id: 190,
      character: "Monarch Tactical Guard",
      credit_id: "607b89b5ae281100404a8bbb",
      order: 37,
    },
    {
      adult: false,
      gender: 2,
      id: 1486626,
      known_for_department: "Production",
      name: "Jason Speer",
      original_name: "Jason Speer",
      popularity: 0.6,
      profile_path: null,
      cast_id: 191,
      character: "Monarch Board Member (uncredited)",
      credit_id: "607b89eb29c626007990af2a",
      order: 38,
    },
    {
      adult: false,
      gender: 2,
      id: 2030686,
      known_for_department: "Acting",
      name: "Sen Shao",
      original_name: "Sen Shao",
      popularity: 0.828,
      profile_path: null,
      cast_id: 193,
      character: "Thug (uncredited)",
      credit_id: "607b8a26746457005892f4dc",
      order: 40,
    },
    {
      adult: false,
      gender: 2,
      id: 1879911,
      known_for_department: "Acting",
      name: "Scott M. Schewe",
      original_name: "Scott M. Schewe",
      popularity: 0.6,
      profile_path: null,
      cast_id: 195,
      character: "Fisherman (uncredited)",
      credit_id: "607b8a6143d9b10057d93ed8",
      order: 42,
    },
    {
      adult: false,
      gender: 2,
      id: 2965914,
      known_for_department: "Acting",
      name: "Charles Sans",
      original_name: "Charles Sans",
      popularity: 1.96,
      profile_path: null,
      cast_id: 197,
      character: "Apex Guard (uncredited)",
      credit_id: "607b8a9cf263ba007094aff8",
      order: 44,
    },
    {
      adult: false,
      gender: 1,
      id: 1244248,
      known_for_department: "Acting",
      name: "Tasneem Roc",
      original_name: "Tasneem Roc",
      popularity: 1.822,
      profile_path: "/ilkyHt7YpN7bNTYzhODXWR0QnwN.jpg",
      cast_id: 198,
      character: "Reporter (uncredited)",
      credit_id: "607b8b24aa659e0078dccbde",
      order: 45,
    },
    {
      adult: false,
      gender: 2,
      id: 2573855,
      known_for_department: "Acting",
      name: "Diezel Ramos",
      original_name: "Diezel Ramos",
      popularity: 0.6,
      profile_path: "/uoMRnPYtWbKSgTY7LdeUPblruP1.jpg",
      cast_id: 199,
      character: "Monarch Military (uncredited)",
      credit_id: "607b8b41ab68490029ca6270",
      order: 46,
    },
    {
      adult: false,
      gender: 2,
      id: 1840497,
      known_for_department: "Acting",
      name: "Jon Quested",
      original_name: "Jon Quested",
      popularity: 1.052,
      profile_path: "/7tpHhDx4I9ysdcBKa8OXKdxH8Uj.jpg",
      cast_id: 200,
      character: "Construction Worker (uncredited)",
      credit_id: "607b8b5a29c626004127d4dc",
      order: 47,
    },
    {
      adult: false,
      gender: 2,
      id: 2269093,
      known_for_department: "Acting",
      name: "Joel Pierce",
      original_name: "Joel Pierce",
      popularity: 1.068,
      profile_path: "/n1CwK63h1wgYozM9nMt2KPdQI5z.jpg",
      cast_id: 201,
      character: "Monarch Tech #2 (uncredited)",
      credit_id: "607b8b859408ec0057c12215",
      order: 48,
    },
    {
      adult: false,
      gender: 1,
      id: 2537658,
      known_for_department: "Acting",
      name: "Sofia Nolan",
      original_name: "Sofia Nolan",
      popularity: 0.6,
      profile_path: "/jKTdzMjfSXqlxj9vkHqG4wVj3BS.jpg",
      cast_id: 202,
      character: "Mean Girl (uncredited)",
      credit_id: "607b8c329661fc005883cddb",
      order: 49,
    },
    {
      adult: false,
      gender: 2,
      id: 1879895,
      known_for_department: "Acting",
      name: "Shawn McBride",
      original_name: "Shawn McBride",
      popularity: 0.652,
      profile_path: null,
      cast_id: 204,
      character: "Fisherman (uncredited)",
      credit_id: "607b8c86713ed40058d7677e",
      order: 51,
    },
    {
      adult: false,
      gender: 2,
      id: 2545358,
      known_for_department: "Acting",
      name: "Clay Mason",
      original_name: "Clay Mason",
      popularity: 0.6,
      profile_path: null,
      cast_id: 206,
      character: "Refugee (uncredited)",
      credit_id: "607b8cc501b1ca0077a40cf4",
      order: 53,
    },
    {
      adult: false,
      gender: 1,
      id: 1338706,
      known_for_department: "Acting",
      name: "Victoria Liu",
      original_name: "Victoria Liu",
      popularity: 0.6,
      profile_path: null,
      cast_id: 209,
      character: "HEAV Pilot #3 (uncredited)",
      credit_id: "607b8d162b8a43003fc56f24",
      order: 56,
    },
    {
      adult: false,
      gender: 2,
      id: 2267140,
      known_for_department: "Acting",
      name: "Sonny Le",
      original_name: "Sonny Le",
      popularity: 0.6,
      profile_path: "/6ADWAGjO5ANMpp19Y7AlkWxNC8C.jpg",
      cast_id: 211,
      character: "Thug (uncredited)",
      credit_id: "607b8d55713ed40058d768a5",
      order: 58,
    },
    {
      adult: false,
      gender: 1,
      id: 2969884,
      known_for_department: "Acting",
      name: "Santi Lawson",
      original_name: "Santi Lawson",
      popularity: 0.6,
      profile_path: "/sJyDK4U2984rtybdhh2rqZPbAAX.jpg",
      cast_id: 212,
      character: "Apex Lab Tech (uncredited)",
      credit_id: "607b8d7a7e34830058aa98fd",
      order: 59,
    },
  ],
};
